package com.identityplatform.core.domain;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.Instant;

import static org.assertj.core.api.Assertions.*;

@DisplayName("BaseEntity tests")
class BaseEntityTest {

    // Test entity that extends BaseEntity
    private static class TestEntity extends BaseEntity {
        private String name;
        public TestEntity(String name) { this.name = name; }
    }

    @Test
    @DisplayName("id: is UUID type")
    void id_isUUID() {
        TestEntity entity = new TestEntity("test");
        // ID will be null before persist (generated by JPA)
        // After save it will be a UUID
        assertThat(entity.getId()).isNull();
    }

    @Test
    @DisplayName("createdAt: is set by JPA Auditing")
    void createdAt_isAudited() {
        TestEntity entity = new TestEntity("test");
        // Before persist: null
        assertThat(entity.getCreatedAt()).isNull();
    }

    @Test
    @DisplayName("updatedAt: is set by JPA Auditing")
    void updatedAt_isAudited() {
        TestEntity entity = new TestEntity("test");
        assertThat(entity.getUpdatedAt()).isNull();
    }

    @Test
    @DisplayName("deleted: default = false")
    void deleted_defaultFalse() {
        TestEntity entity = new TestEntity("test");
        assertThat(entity.isDeleted()).isFalse();
    }

    @Test
    @DisplayName("deleted: can be set to true (soft-delete)")
    void deleted_canBeSetTrue() {
        TestEntity entity = new TestEntity("test");
        entity.setDeleted(true);
        assertThat(entity.isDeleted()).isTrue();
    }

    @Test
    @DisplayName("BaseEntity implements correct getters/setters")
    void basEntity_hasAllFields() {
        TestEntity entity = new TestEntity("test");
        entity.setId(java.util.UUID.randomUUID());
        entity.setCreatedAt(Instant.now());
        entity.setUpdatedAt(Instant.now());
        entity.setDeleted(false);

        assertThat(entity.getId()).isNotNull();
        assertThat(entity.getCreatedAt()).isNotNull();
        assertThat(entity.getUpdatedAt()).isNotNull();
        assertThat(entity.isDeleted()).isFalse();
    }

    @Test
    @DisplayName("BaseEntity: @MappedSuperclass is correct for inheritance")
    void basEntity_mappedSuperclass() {
        // Verify TestEntity extends BaseEntity
        assertThat(BaseEntity.class).isAssignableFrom(TestEntity.class);
        assertThat(TestEntity.class.getSuperclass()).isEqualTo(BaseEntity.class);
    }
}
